// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: account/v3/account_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kin.Agora.Account.V3 {

  /// <summary>Holder for reflection information generated from account/v3/account_service.proto</summary>
  public static partial class AccountServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for account/v3/account_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AccountServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBhY2NvdW50L3YzL2FjY291bnRfc2VydmljZS5wcm90bxIUa2luLmFnb3Jh",
            "LmFjY291bnQudjMaFWNvbW1vbi92My9tb2RlbC5wcm90byJyCgtBY2NvdW50",
            "SW5mbxI5CgphY2NvdW50X2lkGAEgASgLMiUua2luLmFnb3JhLmNvbW1vbi52",
            "My5TdGVsbGFyQWNjb3VudElkEhcKD3NlcXVlbmNlX251bWJlchgCIAEoAxIP",
            "CgdiYWxhbmNlGAMgASgDIlEKFENyZWF0ZUFjY291bnRSZXF1ZXN0EjkKCmFj",
            "Y291bnRfaWQYASABKAsyJS5raW4uYWdvcmEuY29tbW9uLnYzLlN0ZWxsYXJB",
            "Y2NvdW50SWQisgEKFUNyZWF0ZUFjY291bnRSZXNwb25zZRJCCgZyZXN1bHQY",
            "ASABKA4yMi5raW4uYWdvcmEuYWNjb3VudC52My5DcmVhdGVBY2NvdW50UmVz",
            "cG9uc2UuUmVzdWx0EjcKDGFjY291bnRfaW5mbxgCIAEoCzIhLmtpbi5hZ29y",
            "YS5hY2NvdW50LnYzLkFjY291bnRJbmZvIhwKBlJlc3VsdBIGCgJPSxAAEgoK",
            "BkVYSVNUUxABIlIKFUdldEFjY291bnRJbmZvUmVxdWVzdBI5CgphY2NvdW50",
            "X2lkGAEgASgLMiUua2luLmFnb3JhLmNvbW1vbi52My5TdGVsbGFyQWNjb3Vu",
            "dElkIrcBChZHZXRBY2NvdW50SW5mb1Jlc3BvbnNlEkMKBnJlc3VsdBgBIAEo",
            "DjIzLmtpbi5hZ29yYS5hY2NvdW50LnYzLkdldEFjY291bnRJbmZvUmVzcG9u",
            "c2UuUmVzdWx0EjcKDGFjY291bnRfaW5mbxgCIAEoCzIhLmtpbi5hZ29yYS5h",
            "Y2NvdW50LnYzLkFjY291bnRJbmZvIh8KBlJlc3VsdBIGCgJPSxAAEg0KCU5P",
            "VF9GT1VORBABIk0KEEdldEV2ZW50c1JlcXVlc3QSOQoKYWNjb3VudF9pZBgB",
            "IAEoCzIlLmtpbi5hZ29yYS5jb21tb24udjMuU3RlbGxhckFjY291bnRJZCKL",
            "AQoGRXZlbnRzEjMKBnJlc3VsdBgBIAEoDjIjLmtpbi5hZ29yYS5hY2NvdW50",
            "LnYzLkV2ZW50cy5SZXN1bHQSKwoGZXZlbnRzGAIgAygLMhsua2luLmFnb3Jh",
            "LmFjY291bnQudjMuRXZlbnQiHwoGUmVzdWx0EgYKAk9LEAASDQoJTk9UX0ZP",
            "VU5EEAEingEKBUV2ZW50EkgKFGFjY291bnRfdXBkYXRlX2V2ZW50GAEgASgL",
            "Migua2luLmFnb3JhLmFjY291bnQudjMuQWNjb3VudFVwZGF0ZUV2ZW50SAAS",
            "QwoRdHJhbnNhY3Rpb25fZXZlbnQYAiABKAsyJi5raW4uYWdvcmEuYWNjb3Vu",
            "dC52My5UcmFuc2FjdGlvbkV2ZW50SABCBgoEdHlwZSJNChJBY2NvdW50VXBk",
            "YXRlRXZlbnQSNwoMYWNjb3VudF9pbmZvGAEgASgLMiEua2luLmFnb3JhLmFj",
            "Y291bnQudjMuQWNjb3VudEluZm8iPAoQVHJhbnNhY3Rpb25FdmVudBIUCgxl",
            "bnZlbG9wZV94ZHIYASABKAwSEgoKcmVzdWx0X3hkchgCIAEoDDK1AgoHQWNj",
            "b3VudBJoCg1DcmVhdGVBY2NvdW50Eioua2luLmFnb3JhLmFjY291bnQudjMu",
            "Q3JlYXRlQWNjb3VudFJlcXVlc3QaKy5raW4uYWdvcmEuYWNjb3VudC52My5D",
            "cmVhdGVBY2NvdW50UmVzcG9uc2USawoOR2V0QWNjb3VudEluZm8SKy5raW4u",
            "YWdvcmEuYWNjb3VudC52My5HZXRBY2NvdW50SW5mb1JlcXVlc3QaLC5raW4u",
            "YWdvcmEuYWNjb3VudC52My5HZXRBY2NvdW50SW5mb1Jlc3BvbnNlElMKCUdl",
            "dEV2ZW50cxImLmtpbi5hZ29yYS5hY2NvdW50LnYzLkdldEV2ZW50c1JlcXVl",
            "c3QaHC5raW4uYWdvcmEuYWNjb3VudC52My5FdmVudHMwAUJ1Chxvcmcua2lu",
            "LmFnb3JhLmdlbi5hY2NvdW50LnYzWkZnaXRodWIuY29tL2tpbmVjb3N5c3Rl",
            "bS9hZ29yYS1hcGktaW50ZXJuYWwvZ2VucHJvdG8vYWNjb3VudC92MzthY2Nv",
            "dW50ogIMQVBCQWNjb3VudFYzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kin.Agora.Common.V3.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.AccountInfo), global::Kin.Agora.Account.V3.AccountInfo.Parser, new[]{ "AccountId", "SequenceNumber", "Balance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.CreateAccountRequest), global::Kin.Agora.Account.V3.CreateAccountRequest.Parser, new[]{ "AccountId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.CreateAccountResponse), global::Kin.Agora.Account.V3.CreateAccountResponse.Parser, new[]{ "Result", "AccountInfo" }, null, new[]{ typeof(global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.GetAccountInfoRequest), global::Kin.Agora.Account.V3.GetAccountInfoRequest.Parser, new[]{ "AccountId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.GetAccountInfoResponse), global::Kin.Agora.Account.V3.GetAccountInfoResponse.Parser, new[]{ "Result", "AccountInfo" }, null, new[]{ typeof(global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.GetEventsRequest), global::Kin.Agora.Account.V3.GetEventsRequest.Parser, new[]{ "AccountId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.Events), global::Kin.Agora.Account.V3.Events.Parser, new[]{ "Result", "Events_" }, null, new[]{ typeof(global::Kin.Agora.Account.V3.Events.Types.Result) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.Event), global::Kin.Agora.Account.V3.Event.Parser, new[]{ "AccountUpdateEvent", "TransactionEvent" }, new[]{ "Type" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.AccountUpdateEvent), global::Kin.Agora.Account.V3.AccountUpdateEvent.Parser, new[]{ "AccountInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Account.V3.TransactionEvent), global::Kin.Agora.Account.V3.TransactionEvent.Parser, new[]{ "EnvelopeXdr", "ResultXdr" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AccountInfo : pb::IMessage<AccountInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccountInfo> _parser = new pb::MessageParser<AccountInfo>(() => new AccountInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AccountInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountInfo(AccountInfo other) : this() {
      accountId_ = other.accountId_ != null ? other.accountId_.Clone() : null;
      sequenceNumber_ = other.sequenceNumber_;
      balance_ = other.balance_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountInfo Clone() {
      return new AccountInfo(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private global::Kin.Agora.Common.V3.StellarAccountId accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V3.StellarAccountId AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "sequence_number" field.</summary>
    public const int SequenceNumberFieldNumber = 2;
    private long sequenceNumber_;
    /// <summary>
    /// The last known sequence number of the account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SequenceNumber {
      get { return sequenceNumber_; }
      set {
        sequenceNumber_ = value;
      }
    }

    /// <summary>Field number for the "balance" field.</summary>
    public const int BalanceFieldNumber = 3;
    private long balance_;
    /// <summary>
    /// The last known balance, in quarks, of the account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Balance {
      get { return balance_; }
      set {
        balance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AccountInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AccountInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountId, other.AccountId)) return false;
      if (SequenceNumber != other.SequenceNumber) return false;
      if (Balance != other.Balance) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (accountId_ != null) hash ^= AccountId.GetHashCode();
      if (SequenceNumber != 0L) hash ^= SequenceNumber.GetHashCode();
      if (Balance != 0L) hash ^= Balance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (SequenceNumber != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SequenceNumber);
      }
      if (Balance != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Balance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (SequenceNumber != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SequenceNumber);
      }
      if (Balance != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Balance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (accountId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountId);
      }
      if (SequenceNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SequenceNumber);
      }
      if (Balance != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Balance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AccountInfo other) {
      if (other == null) {
        return;
      }
      if (other.accountId_ != null) {
        if (accountId_ == null) {
          AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
        }
        AccountId.MergeFrom(other.AccountId);
      }
      if (other.SequenceNumber != 0L) {
        SequenceNumber = other.SequenceNumber;
      }
      if (other.Balance != 0L) {
        Balance = other.Balance;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
          case 16: {
            SequenceNumber = input.ReadInt64();
            break;
          }
          case 24: {
            Balance = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
          case 16: {
            SequenceNumber = input.ReadInt64();
            break;
          }
          case 24: {
            Balance = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreateAccountRequest : pb::IMessage<CreateAccountRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateAccountRequest> _parser = new pb::MessageParser<CreateAccountRequest>(() => new CreateAccountRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateAccountRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountRequest(CreateAccountRequest other) : this() {
      accountId_ = other.accountId_ != null ? other.accountId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountRequest Clone() {
      return new CreateAccountRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private global::Kin.Agora.Common.V3.StellarAccountId accountId_;
    /// <summary>
    /// Account to be created
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V3.StellarAccountId AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateAccountRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateAccountRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountId, other.AccountId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (accountId_ != null) hash ^= AccountId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (accountId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateAccountRequest other) {
      if (other == null) {
        return;
      }
      if (other.accountId_ != null) {
        if (accountId_ == null) {
          AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
        }
        AccountId.MergeFrom(other.AccountId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreateAccountResponse : pb::IMessage<CreateAccountResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateAccountResponse> _parser = new pb::MessageParser<CreateAccountResponse>(() => new CreateAccountResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateAccountResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountResponse(CreateAccountResponse other) : this() {
      result_ = other.result_;
      accountInfo_ = other.accountInfo_ != null ? other.accountInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateAccountResponse Clone() {
      return new CreateAccountResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result result_ = global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "account_info" field.</summary>
    public const int AccountInfoFieldNumber = 2;
    private global::Kin.Agora.Account.V3.AccountInfo accountInfo_;
    /// <summary>
    /// Will be present if the account was created or already existed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.AccountInfo AccountInfo {
      get { return accountInfo_; }
      set {
        accountInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateAccountResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateAccountResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(AccountInfo, other.AccountInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result.Ok) hash ^= Result.GetHashCode();
      if (accountInfo_ != null) hash ^= AccountInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (accountInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AccountInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (accountInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AccountInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (accountInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateAccountResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result.Ok) {
        Result = other.Result;
      }
      if (other.accountInfo_ != null) {
        if (accountInfo_ == null) {
          AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
        }
        AccountInfo.MergeFrom(other.AccountInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (accountInfo_ == null) {
              AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
            }
            input.ReadMessage(AccountInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Account.V3.CreateAccountResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (accountInfo_ == null) {
              AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
            }
            input.ReadMessage(AccountInfo);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the CreateAccountResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("EXISTS")] Exists = 1,
      }

    }
    #endregion

  }

  public sealed partial class GetAccountInfoRequest : pb::IMessage<GetAccountInfoRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetAccountInfoRequest> _parser = new pb::MessageParser<GetAccountInfoRequest>(() => new GetAccountInfoRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAccountInfoRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAccountInfoRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAccountInfoRequest(GetAccountInfoRequest other) : this() {
      accountId_ = other.accountId_ != null ? other.accountId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAccountInfoRequest Clone() {
      return new GetAccountInfoRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private global::Kin.Agora.Common.V3.StellarAccountId accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V3.StellarAccountId AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAccountInfoRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAccountInfoRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountId, other.AccountId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (accountId_ != null) hash ^= AccountId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (accountId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAccountInfoRequest other) {
      if (other == null) {
        return;
      }
      if (other.accountId_ != null) {
        if (accountId_ == null) {
          AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
        }
        AccountId.MergeFrom(other.AccountId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetAccountInfoResponse : pb::IMessage<GetAccountInfoResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetAccountInfoResponse> _parser = new pb::MessageParser<GetAccountInfoResponse>(() => new GetAccountInfoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAccountInfoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAccountInfoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAccountInfoResponse(GetAccountInfoResponse other) : this() {
      result_ = other.result_;
      accountInfo_ = other.accountInfo_ != null ? other.accountInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAccountInfoResponse Clone() {
      return new GetAccountInfoResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result result_ = global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "account_info" field.</summary>
    public const int AccountInfoFieldNumber = 2;
    private global::Kin.Agora.Account.V3.AccountInfo accountInfo_;
    /// <summary>
    /// Present iff result == Result::OK
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.AccountInfo AccountInfo {
      get { return accountInfo_; }
      set {
        accountInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAccountInfoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAccountInfoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(AccountInfo, other.AccountInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result.Ok) hash ^= Result.GetHashCode();
      if (accountInfo_ != null) hash ^= AccountInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (accountInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AccountInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (accountInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AccountInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (accountInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAccountInfoResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result.Ok) {
        Result = other.Result;
      }
      if (other.accountInfo_ != null) {
        if (accountInfo_ == null) {
          AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
        }
        AccountInfo.MergeFrom(other.AccountInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (accountInfo_ == null) {
              AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
            }
            input.ReadMessage(AccountInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Account.V3.GetAccountInfoResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (accountInfo_ == null) {
              AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
            }
            input.ReadMessage(AccountInfo);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GetAccountInfoResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("OK")] Ok = 0,
        /// <summary>
        /// The specified account could not be found.
        /// </summary>
        [pbr::OriginalName("NOT_FOUND")] NotFound = 1,
      }

    }
    #endregion

  }

  public sealed partial class GetEventsRequest : pb::IMessage<GetEventsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetEventsRequest> _parser = new pb::MessageParser<GetEventsRequest>(() => new GetEventsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetEventsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEventsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEventsRequest(GetEventsRequest other) : this() {
      accountId_ = other.accountId_ != null ? other.accountId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEventsRequest Clone() {
      return new GetEventsRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private global::Kin.Agora.Common.V3.StellarAccountId accountId_;
    /// <summary>
    /// The id of the account to stream events for
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V3.StellarAccountId AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetEventsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetEventsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountId, other.AccountId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (accountId_ != null) hash ^= AccountId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (accountId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetEventsRequest other) {
      if (other == null) {
        return;
      }
      if (other.accountId_ != null) {
        if (accountId_ == null) {
          AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
        }
        AccountId.MergeFrom(other.AccountId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V3.StellarAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Events : pb::IMessage<Events>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Events> _parser = new pb::MessageParser<Events>(() => new Events());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Events> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Events() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Events(Events other) : this() {
      result_ = other.result_;
      events_ = other.events_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Events Clone() {
      return new Events(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Kin.Agora.Account.V3.Events.Types.Result result_ = global::Kin.Agora.Account.V3.Events.Types.Result.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.Events.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int Events_FieldNumber = 2;
    private static readonly pb::FieldCodec<global::Kin.Agora.Account.V3.Event> _repeated_events_codec
        = pb::FieldCodec.ForMessage(18, global::Kin.Agora.Account.V3.Event.Parser);
    private readonly pbc::RepeatedField<global::Kin.Agora.Account.V3.Event> events_ = new pbc::RepeatedField<global::Kin.Agora.Account.V3.Event>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Kin.Agora.Account.V3.Event> Events_ {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Events);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Events other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!events_.Equals(other.events_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Kin.Agora.Account.V3.Events.Types.Result.Ok) hash ^= Result.GetHashCode();
      hash ^= events_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Kin.Agora.Account.V3.Events.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      events_.WriteTo(output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Kin.Agora.Account.V3.Events.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      events_.WriteTo(ref output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Kin.Agora.Account.V3.Events.Types.Result.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      size += events_.CalculateSize(_repeated_events_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Events other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Kin.Agora.Account.V3.Events.Types.Result.Ok) {
        Result = other.Result;
      }
      events_.Add(other.events_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Account.V3.Events.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Account.V3.Events.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            events_.AddEntriesFrom(ref input, _repeated_events_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Events message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("OK")] Ok = 0,
        /// <summary>
        /// The specified account could not be found.
        /// </summary>
        [pbr::OriginalName("NOT_FOUND")] NotFound = 1,
      }

    }
    #endregion

  }

  public sealed partial class Event : pb::IMessage<Event>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Event> _parser = new pb::MessageParser<Event>(() => new Event());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Event> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event(Event other) : this() {
      switch (other.TypeCase) {
        case TypeOneofCase.AccountUpdateEvent:
          AccountUpdateEvent = other.AccountUpdateEvent.Clone();
          break;
        case TypeOneofCase.TransactionEvent:
          TransactionEvent = other.TransactionEvent.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Event Clone() {
      return new Event(this);
    }

    /// <summary>Field number for the "account_update_event" field.</summary>
    public const int AccountUpdateEventFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.AccountUpdateEvent AccountUpdateEvent {
      get { return typeCase_ == TypeOneofCase.AccountUpdateEvent ? (global::Kin.Agora.Account.V3.AccountUpdateEvent) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.AccountUpdateEvent;
      }
    }

    /// <summary>Field number for the "transaction_event" field.</summary>
    public const int TransactionEventFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.TransactionEvent TransactionEvent {
      get { return typeCase_ == TypeOneofCase.TransactionEvent ? (global::Kin.Agora.Account.V3.TransactionEvent) type_ : null; }
      set {
        type_ = value;
        typeCase_ = value == null ? TypeOneofCase.None : TypeOneofCase.TransactionEvent;
      }
    }

    private object type_;
    /// <summary>Enum of possible cases for the "type" oneof.</summary>
    public enum TypeOneofCase {
      None = 0,
      AccountUpdateEvent = 1,
      TransactionEvent = 2,
    }
    private TypeOneofCase typeCase_ = TypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TypeOneofCase TypeCase {
      get { return typeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearType() {
      typeCase_ = TypeOneofCase.None;
      type_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Event);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Event other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountUpdateEvent, other.AccountUpdateEvent)) return false;
      if (!object.Equals(TransactionEvent, other.TransactionEvent)) return false;
      if (TypeCase != other.TypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (typeCase_ == TypeOneofCase.AccountUpdateEvent) hash ^= AccountUpdateEvent.GetHashCode();
      if (typeCase_ == TypeOneofCase.TransactionEvent) hash ^= TransactionEvent.GetHashCode();
      hash ^= (int) typeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (typeCase_ == TypeOneofCase.AccountUpdateEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountUpdateEvent);
      }
      if (typeCase_ == TypeOneofCase.TransactionEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(TransactionEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (typeCase_ == TypeOneofCase.AccountUpdateEvent) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountUpdateEvent);
      }
      if (typeCase_ == TypeOneofCase.TransactionEvent) {
        output.WriteRawTag(18);
        output.WriteMessage(TransactionEvent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (typeCase_ == TypeOneofCase.AccountUpdateEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountUpdateEvent);
      }
      if (typeCase_ == TypeOneofCase.TransactionEvent) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TransactionEvent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Event other) {
      if (other == null) {
        return;
      }
      switch (other.TypeCase) {
        case TypeOneofCase.AccountUpdateEvent:
          if (AccountUpdateEvent == null) {
            AccountUpdateEvent = new global::Kin.Agora.Account.V3.AccountUpdateEvent();
          }
          AccountUpdateEvent.MergeFrom(other.AccountUpdateEvent);
          break;
        case TypeOneofCase.TransactionEvent:
          if (TransactionEvent == null) {
            TransactionEvent = new global::Kin.Agora.Account.V3.TransactionEvent();
          }
          TransactionEvent.MergeFrom(other.TransactionEvent);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Kin.Agora.Account.V3.AccountUpdateEvent subBuilder = new global::Kin.Agora.Account.V3.AccountUpdateEvent();
            if (typeCase_ == TypeOneofCase.AccountUpdateEvent) {
              subBuilder.MergeFrom(AccountUpdateEvent);
            }
            input.ReadMessage(subBuilder);
            AccountUpdateEvent = subBuilder;
            break;
          }
          case 18: {
            global::Kin.Agora.Account.V3.TransactionEvent subBuilder = new global::Kin.Agora.Account.V3.TransactionEvent();
            if (typeCase_ == TypeOneofCase.TransactionEvent) {
              subBuilder.MergeFrom(TransactionEvent);
            }
            input.ReadMessage(subBuilder);
            TransactionEvent = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Kin.Agora.Account.V3.AccountUpdateEvent subBuilder = new global::Kin.Agora.Account.V3.AccountUpdateEvent();
            if (typeCase_ == TypeOneofCase.AccountUpdateEvent) {
              subBuilder.MergeFrom(AccountUpdateEvent);
            }
            input.ReadMessage(subBuilder);
            AccountUpdateEvent = subBuilder;
            break;
          }
          case 18: {
            global::Kin.Agora.Account.V3.TransactionEvent subBuilder = new global::Kin.Agora.Account.V3.TransactionEvent();
            if (typeCase_ == TypeOneofCase.TransactionEvent) {
              subBuilder.MergeFrom(TransactionEvent);
            }
            input.ReadMessage(subBuilder);
            TransactionEvent = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// An event that gets sent when an account's information has changed.
  /// </summary>
  public sealed partial class AccountUpdateEvent : pb::IMessage<AccountUpdateEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AccountUpdateEvent> _parser = new pb::MessageParser<AccountUpdateEvent>(() => new AccountUpdateEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AccountUpdateEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountUpdateEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountUpdateEvent(AccountUpdateEvent other) : this() {
      accountInfo_ = other.accountInfo_ != null ? other.accountInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AccountUpdateEvent Clone() {
      return new AccountUpdateEvent(this);
    }

    /// <summary>Field number for the "account_info" field.</summary>
    public const int AccountInfoFieldNumber = 1;
    private global::Kin.Agora.Account.V3.AccountInfo accountInfo_;
    /// <summary>
    /// The account information most recently obtained by the service.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Account.V3.AccountInfo AccountInfo {
      get { return accountInfo_; }
      set {
        accountInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AccountUpdateEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AccountUpdateEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountInfo, other.AccountInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (accountInfo_ != null) hash ^= AccountInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accountInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accountInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (accountInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AccountUpdateEvent other) {
      if (other == null) {
        return;
      }
      if (other.accountInfo_ != null) {
        if (accountInfo_ == null) {
          AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
        }
        AccountInfo.MergeFrom(other.AccountInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (accountInfo_ == null) {
              AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
            }
            input.ReadMessage(AccountInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (accountInfo_ == null) {
              AccountInfo = new global::Kin.Agora.Account.V3.AccountInfo();
            }
            input.ReadMessage(AccountInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// An event that gets sent when a transaction related to an account has been
  /// successfully submitted to the blockchain.
  /// </summary>
  public sealed partial class TransactionEvent : pb::IMessage<TransactionEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TransactionEvent> _parser = new pb::MessageParser<TransactionEvent>(() => new TransactionEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TransactionEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Account.V3.AccountServiceReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionEvent(TransactionEvent other) : this() {
      envelopeXdr_ = other.envelopeXdr_;
      resultXdr_ = other.resultXdr_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TransactionEvent Clone() {
      return new TransactionEvent(this);
    }

    /// <summary>Field number for the "envelope_xdr" field.</summary>
    public const int EnvelopeXdrFieldNumber = 1;
    private pb::ByteString envelopeXdr_ = pb::ByteString.Empty;
    /// <summary>
    /// The transaction envelope XDR.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString EnvelopeXdr {
      get { return envelopeXdr_; }
      set {
        envelopeXdr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "result_xdr" field.</summary>
    public const int ResultXdrFieldNumber = 2;
    private pb::ByteString resultXdr_ = pb::ByteString.Empty;
    /// <summary>
    /// The transaction result XDR.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ResultXdr {
      get { return resultXdr_; }
      set {
        resultXdr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TransactionEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TransactionEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnvelopeXdr != other.EnvelopeXdr) return false;
      if (ResultXdr != other.ResultXdr) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EnvelopeXdr.Length != 0) hash ^= EnvelopeXdr.GetHashCode();
      if (ResultXdr.Length != 0) hash ^= ResultXdr.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EnvelopeXdr.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(EnvelopeXdr);
      }
      if (ResultXdr.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(ResultXdr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EnvelopeXdr.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(EnvelopeXdr);
      }
      if (ResultXdr.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(ResultXdr);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EnvelopeXdr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(EnvelopeXdr);
      }
      if (ResultXdr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ResultXdr);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TransactionEvent other) {
      if (other == null) {
        return;
      }
      if (other.EnvelopeXdr.Length != 0) {
        EnvelopeXdr = other.EnvelopeXdr;
      }
      if (other.ResultXdr.Length != 0) {
        ResultXdr = other.ResultXdr;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            EnvelopeXdr = input.ReadBytes();
            break;
          }
          case 18: {
            ResultXdr = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            EnvelopeXdr = input.ReadBytes();
            break;
          }
          case 18: {
            ResultXdr = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
