// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: airdrop/v4/airdrop_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kin.Agora.Airdrop.V4 {

  /// <summary>Holder for reflection information generated from airdrop/v4/airdrop_service.proto</summary>
  public static partial class AirdropServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for airdrop/v4/airdrop_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AirdropServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBhaXJkcm9wL3Y0L2FpcmRyb3Bfc2VydmljZS5wcm90bxIUa2luLmFnb3Jh",
            "LmFpcmRyb3AudjQaFWNvbW1vbi92NC9tb2RlbC5wcm90byKWAQoVUmVxdWVz",
            "dEFpcmRyb3BSZXF1ZXN0EjgKCmFjY291bnRfaWQYASABKAsyJC5raW4uYWdv",
            "cmEuY29tbW9uLnY0LlNvbGFuYUFjY291bnRJZBIOCgZxdWFya3MYAiABKAQS",
            "MwoKY29tbWl0bWVudBgDIAEoDjIfLmtpbi5hZ29yYS5jb21tb24udjQuQ29t",
            "bWl0bWVudCLSAQoWUmVxdWVzdEFpcmRyb3BSZXNwb25zZRJDCgZyZXN1bHQY",
            "ASABKA4yMy5raW4uYWdvcmEuYWlyZHJvcC52NC5SZXF1ZXN0QWlyZHJvcFJl",
            "c3BvbnNlLlJlc3VsdBI8CglzaWduYXR1cmUYAiABKAsyKS5raW4uYWdvcmEu",
            "Y29tbW9uLnY0LlRyYW5zYWN0aW9uU2lnbmF0dXJlIjUKBlJlc3VsdBIGCgJP",
            "SxAAEg0KCU5PVF9GT1VORBABEhQKEElOU1VGRklDSUVOVF9LSU4QAjJ2CgdB",
            "aXJkcm9wEmsKDlJlcXVlc3RBaXJkcm9wEisua2luLmFnb3JhLmFpcmRyb3Au",
            "djQuUmVxdWVzdEFpcmRyb3BSZXF1ZXN0Giwua2luLmFnb3JhLmFpcmRyb3Au",
            "djQuUmVxdWVzdEFpcmRyb3BSZXNwb25zZUJ1Chxvcmcua2luLmFnb3JhLmdl",
            "bi5haXJkcm9wLnY0WkZnaXRodWIuY29tL2tpbmVjb3N5c3RlbS9hZ29yYS1h",
            "cGktaW50ZXJuYWwvZ2VucHJvdG8vYWlyZHJvcC92NDthaXJkcm9wogIMQVBC",
            "QWlyZHJvcFY0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Kin.Agora.Common.V4.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Airdrop.V4.RequestAirdropRequest), global::Kin.Agora.Airdrop.V4.RequestAirdropRequest.Parser, new[]{ "AccountId", "Quarks", "Commitment" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Kin.Agora.Airdrop.V4.RequestAirdropResponse), global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Parser, new[]{ "Result", "Signature" }, null, new[]{ typeof(global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RequestAirdropRequest : pb::IMessage<RequestAirdropRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestAirdropRequest> _parser = new pb::MessageParser<RequestAirdropRequest>(() => new RequestAirdropRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestAirdropRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Airdrop.V4.AirdropServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestAirdropRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestAirdropRequest(RequestAirdropRequest other) : this() {
      accountId_ = other.accountId_ != null ? other.accountId_.Clone() : null;
      quarks_ = other.quarks_;
      commitment_ = other.commitment_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestAirdropRequest Clone() {
      return new RequestAirdropRequest(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private global::Kin.Agora.Common.V4.SolanaAccountId accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V4.SolanaAccountId AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "quarks" field.</summary>
    public const int QuarksFieldNumber = 2;
    private ulong quarks_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Quarks {
      get { return quarks_; }
      set {
        quarks_ = value;
      }
    }

    /// <summary>Field number for the "commitment" field.</summary>
    public const int CommitmentFieldNumber = 3;
    private global::Kin.Agora.Common.V4.Commitment commitment_ = global::Kin.Agora.Common.V4.Commitment.Recent;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V4.Commitment Commitment {
      get { return commitment_; }
      set {
        commitment_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestAirdropRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestAirdropRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(AccountId, other.AccountId)) return false;
      if (Quarks != other.Quarks) return false;
      if (Commitment != other.Commitment) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (accountId_ != null) hash ^= AccountId.GetHashCode();
      if (Quarks != 0UL) hash ^= Quarks.GetHashCode();
      if (Commitment != global::Kin.Agora.Common.V4.Commitment.Recent) hash ^= Commitment.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (Quarks != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Quarks);
      }
      if (Commitment != global::Kin.Agora.Common.V4.Commitment.Recent) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Commitment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (accountId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(AccountId);
      }
      if (Quarks != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Quarks);
      }
      if (Commitment != global::Kin.Agora.Common.V4.Commitment.Recent) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Commitment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (accountId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AccountId);
      }
      if (Quarks != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Quarks);
      }
      if (Commitment != global::Kin.Agora.Common.V4.Commitment.Recent) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Commitment);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestAirdropRequest other) {
      if (other == null) {
        return;
      }
      if (other.accountId_ != null) {
        if (accountId_ == null) {
          AccountId = new global::Kin.Agora.Common.V4.SolanaAccountId();
        }
        AccountId.MergeFrom(other.AccountId);
      }
      if (other.Quarks != 0UL) {
        Quarks = other.Quarks;
      }
      if (other.Commitment != global::Kin.Agora.Common.V4.Commitment.Recent) {
        Commitment = other.Commitment;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V4.SolanaAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
          case 16: {
            Quarks = input.ReadUInt64();
            break;
          }
          case 24: {
            Commitment = (global::Kin.Agora.Common.V4.Commitment) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (accountId_ == null) {
              AccountId = new global::Kin.Agora.Common.V4.SolanaAccountId();
            }
            input.ReadMessage(AccountId);
            break;
          }
          case 16: {
            Quarks = input.ReadUInt64();
            break;
          }
          case 24: {
            Commitment = (global::Kin.Agora.Common.V4.Commitment) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RequestAirdropResponse : pb::IMessage<RequestAirdropResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestAirdropResponse> _parser = new pb::MessageParser<RequestAirdropResponse>(() => new RequestAirdropResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestAirdropResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Kin.Agora.Airdrop.V4.AirdropServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestAirdropResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestAirdropResponse(RequestAirdropResponse other) : this() {
      result_ = other.result_;
      signature_ = other.signature_ != null ? other.signature_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestAirdropResponse Clone() {
      return new RequestAirdropResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result result_ = global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "signature" field.</summary>
    public const int SignatureFieldNumber = 2;
    private global::Kin.Agora.Common.V4.TransactionSignature signature_;
    /// <summary>
    /// The signature of the transaction, if result == Result::OK.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Kin.Agora.Common.V4.TransactionSignature Signature {
      get { return signature_; }
      set {
        signature_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestAirdropResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestAirdropResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(Signature, other.Signature)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result.Ok) hash ^= Result.GetHashCode();
      if (signature_ != null) hash ^= Signature.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (signature_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (signature_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Signature);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (signature_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Signature);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestAirdropResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result.Ok) {
        Result = other.Result;
      }
      if (other.signature_ != null) {
        if (signature_ == null) {
          Signature = new global::Kin.Agora.Common.V4.TransactionSignature();
        }
        Signature.MergeFrom(other.Signature);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (signature_ == null) {
              Signature = new global::Kin.Agora.Common.V4.TransactionSignature();
            }
            input.ReadMessage(Signature);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Kin.Agora.Airdrop.V4.RequestAirdropResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (signature_ == null) {
              Signature = new global::Kin.Agora.Common.V4.TransactionSignature();
            }
            input.ReadMessage(Signature);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RequestAirdropResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("OK")] Ok = 0,
        /// <summary>
        /// The target account does not exist.
        /// </summary>
        [pbr::OriginalName("NOT_FOUND")] NotFound = 1,
        /// <summary>
        /// The airdrop service does not have enough kin.
        /// </summary>
        [pbr::OriginalName("INSUFFICIENT_KIN")] InsufficientKin = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
