// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: metrics/v3/ingestion_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Kin.Agora.Metrics.V3 {
  public static partial class Ingestion
  {
    static readonly string __ServiceName = "kin.agora.metrics.v3.Ingestion";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Kin.Agora.Metrics.V3.SubmitRequest> __Marshaller_kin_agora_metrics_v3_SubmitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Kin.Agora.Metrics.V3.SubmitRequest.Parser));
    static readonly grpc::Marshaller<global::Kin.Agora.Metrics.V3.SubmitResponse> __Marshaller_kin_agora_metrics_v3_SubmitResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Kin.Agora.Metrics.V3.SubmitResponse.Parser));

    static readonly grpc::Method<global::Kin.Agora.Metrics.V3.SubmitRequest, global::Kin.Agora.Metrics.V3.SubmitResponse> __Method_Submit = new grpc::Method<global::Kin.Agora.Metrics.V3.SubmitRequest, global::Kin.Agora.Metrics.V3.SubmitResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Submit",
        __Marshaller_kin_agora_metrics_v3_SubmitRequest,
        __Marshaller_kin_agora_metrics_v3_SubmitResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Kin.Agora.Metrics.V3.IngestionServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Ingestion</summary>
    [grpc::BindServiceMethod(typeof(Ingestion), "BindService")]
    public abstract partial class IngestionBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Kin.Agora.Metrics.V3.SubmitResponse> Submit(global::Kin.Agora.Metrics.V3.SubmitRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Ingestion</summary>
    public partial class IngestionClient : grpc::ClientBase<IngestionClient>
    {
      /// <summary>Creates a new client for Ingestion</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IngestionClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Ingestion that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IngestionClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IngestionClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IngestionClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Kin.Agora.Metrics.V3.SubmitResponse Submit(global::Kin.Agora.Metrics.V3.SubmitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Submit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Kin.Agora.Metrics.V3.SubmitResponse Submit(global::Kin.Agora.Metrics.V3.SubmitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Submit, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Kin.Agora.Metrics.V3.SubmitResponse> SubmitAsync(global::Kin.Agora.Metrics.V3.SubmitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubmitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Kin.Agora.Metrics.V3.SubmitResponse> SubmitAsync(global::Kin.Agora.Metrics.V3.SubmitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Submit, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IngestionClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IngestionClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IngestionBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Submit, serviceImpl.Submit).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IngestionBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Submit, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Kin.Agora.Metrics.V3.SubmitRequest, global::Kin.Agora.Metrics.V3.SubmitResponse>(serviceImpl.Submit));
    }

  }
}
#endregion
