// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: metrics/v3/model.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Kin.Agora.Metrics.V3 {

  /// <summary>Holder for reflection information generated from metrics/v3/model.proto</summary>
  public static partial class ModelReflection {

    #region Descriptor
    /// <summary>File descriptor for metrics/v3/model.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZtZXRyaWNzL3YzL21vZGVsLnByb3RvEhRraW4uYWdvcmEubWV0cmljcy52",
            "M0J1Chxvcmcua2luLmFnb3JhLmdlbi5tZXRyaWNzLnYzWkZnaXRodWIuY29t",
            "L2tpbmVjb3N5c3RlbS9hZ29yYS1hcGktaW50ZXJuYWwvZ2VucHJvdG8vbWV0",
            "cmljcy92MzttZXRyaWNzogIMQVBCTWV0cmljc1YzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
